version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - TYPE=BepInExFull
      - "MODS=
        https://gcdn.thunderstore.io/live/repository/packages/Grantapher-ValheimPlus_Grantapher_Temporary-9.13.0.zip
        "
      - PORT=2456
      - NAME="********"
      - WORLD="********"
      - PASSWORD="********"
      - TZ=Europe/Paris
      - PUBLIC=1
      - AUTO_UPDATE=0
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - ./valheim/server:/home/steam/valheim
    restart: always